# CMS Backend Configuration for Camunda 8.5 - DEFINITIVE FIX
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: cms-backend
  
  profiles:
    active: dev
  
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        default_schema: cms_workflow
    open-in-view: false
    
  security:
    user:
      name: admin
      password: admin123
      
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

# CRITICAL: Use the LEGACY Zeebe configuration format for plaintext
# The new SDK still has issues with plaintext configuration
zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
    worker:
      max-jobs-active: 32
      threads: 1
      default-timeout: 300000  # 5 minutes in milliseconds
      default-poll-interval: 100  # 100ms
    job:
      timeout: 300000
      poll-interval: 100
    message:
      time-to-live: 3600000

# DISABLE the new Camunda client auto-configuration to avoid conflicts
camunda:
  client:
    enabled: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours

# Logging
logging:
  level:
    com.citi.cms: DEBUG
    io.camunda: INFO
    io.grpc: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized